* Meetings
** <2025-02-07 Fri> overleg VAF
- word boundaries te bespreken
- common crawl : filter op periode is voor de crawling tijdens deze periode.  de informatie die hiermee wordt gevonden kan al veel ouder zijn.   enerzijds is dat een probleem.  anderszijds willen we ons ook niet beperken tot enkel nieuwe informatie tijdens deze periode gepubliceerd.  enkele nieuwe info is allicht relevanter voor social media.
- evaluatie criteratie relevant
- evaluatie criteria disinformatie
- bekijken welke data nu juist mee te nemen voor disinformatie?   lijst van URLs?
- feedback VAF : research questions beperken en groeperen.  andere zaken?
- TikTok API : test gedaan, technische verbinding is OK.
- EuroHPC : reminder gestuurd, spam folder student.ou.nl account?
 => Servicedesk, ITF <servicedesk@ou.nl>

AF :
introductie meer uitgebreid
related literature ook meer uitgebreid
ofwel per onderzoeksvraag 1 hoofdstuk
ofwel datapreparatie 1 hoofdstuk, dan model, ...

scenarios 

beslissingen in AF opsommen

https://guides.lib.uni.edu/media-accuracy-media-bia-media-trends/logical-fallacies

filtering, evaluation, ..
perhaps limit to one specific source of migrants.

rumour detection 1 class classification te bekijken?


* links

[[https://emschwartz.me/understanding-the-bm25-full-text-search-algorithm/][BM25 search algorithm]]
https://github.com/Florents-Tselai/WarcDB
https://github.com/iipc/jwarc
https://medium.com/@samuel.schaffhauser/using-the-common-crawl-as-a-data-source-693a41b3baa9
index lijst downloaden op https://medium.com/@samuel.schaffhauser/using-the-common-crawl-as-a-data-source-693a41b3baa9
https://pullpush.io
https://developers.tiktok.com/products/research-api/
https://sf16-va.tiktokcdn.com/obj/eden-va2/lapz_k4_rvarpa/ljhwZthlaukjlkulzlp/form/research-endorsement-letter.pdf
https://vast.ai/
https://www.shepbryan.com/blog/what-is-gguf

let op : er is EU disinfo lab en eu vs disinfo

https://www.disinfo.eu/publications/disinformation-landscape-in-the-netherlands/
https://www.disinfo.eu/publications/disinformation-landscape-in-belgium/

project dat in belgie socials checkte op disinformatie
https://crossover.social/

mee te nemen?
https://www.reddit.com/r/Antwerpen/


https://euvsdisinfo.eu/ukraine/

commonly used narratives :
https://edmo.eu/publications/disinformers-use-similar-arguments-and-techniques-to-steer-hate-against-migrants-from-ukraine-or-the-global-south-2/

** tiktok
[[https://developers.tiktok.com/doc/vce-getting-started][dev account getting started]]
[[https://developers.tiktok.com/research/7467661064878098438][credentials dev account]]
[[https://developers.tiktok.com/doc/research-api-get-started][research api getting started]]
[[https://developers.tiktok.com/doc/client-access-token-management][generate an access token]]
[[https://developers.tiktok.com/doc/research-api-specs-query-videos?enter_method=left_navigation][API reference - query videos]]
[[https://developers.tiktok.com/doc/research-api-specs-query-video-comments?enter_method=left_navigation][API reference - query video comments]]

* datasets

[[https://www.kaggle.com/code/akshayr009/fakenewsdetection]]
https://www.kaggle.com/datasets/corrieaar/disinformation-articles
https://www.kaggle.com/datasets/imuhammad/euvsdisinfo-disinformation-database
