[project]
name = "dataset-reddit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fasttext>=0.9.3",
    "googletrans>=4.0.2",
    "llama-index>=0.12.31",
    "pydantic>=2.11.1",
    "wget>=3.2",
]
